# Generated by Django 2.2.7 on 2019-11-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsenews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.CharField(max_length=200),
        ),
    ]
